---
title: "MA_ Analysis"
author: "Núria Garcia"
date: "5/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
workingDir <- setwd("~/Escritorio/Garcia_Nuria_OmicsTechniques/Exercise_2")
dataDir <- file.path(workingDir, "dades")
resultsDir <- file.path(workingDir, "results")
setwd(resultsDir) #used to change the diretory
```

```{r}
if (!require(BiocManager)) install.packages("BiocManager")

installifnot <- function (pkg){
  if (!require(pkg, character.only=T)){
    BiocManager::install(pkg)
  }else{
    require(pkg, character.only=T)
  }
}
installifnot("pd.mouse430.2")
installifnot("pd.mogene.1.0.st.v1")
installifnot("mogene10sttranscriptcluster.db")
installifnot("oligo")
installifnot("limma")
installifnot("Biobase")
installifnot("genefilter")
installifnot("multtest")
installifnot("annotate")
installifnot("xtable")
installifnot("gplots")
installifnot("scatterplot3d")
```

```{r}
require(GEOquery)
gse <- getGEO("GSE57820")
set <- gse[[1]]
rawData <- set

```


```{r}
targets <-read.csv(file=file.path(dataDir,"taget.txt"), header = TRUE, sep = '')
targets
```

```{r}
sampleNames <- as.character(targets$SampleName) #mirar
  sampleColor <- as.character(targets$Color)
``` 

```{r}
boxplot(rawData, which="all",las=2, main="Intensity distribution of RAW data", 
        cex.axis=0.6, col=sampleColor, names=sampleNames)
```

```{r}
clust.euclid.average <- hclust(dist(t(exprs(rawData))),method="average")
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of RawData", 
     cex=0.7,  hang=-1)
```

```{r}
plotPCA <- function ( X, labels=NULL, colors=NULL, dataDesc="", scale=FALSE, formapunts=NULL, myCex=0.8,...)
{
  pcX<-prcomp(t(X), scale=scale) # o prcomp(t(X))
  loads<- round(pcX$sdev^2/sum(pcX$sdev^2)*100,1)
  xlab<-c(paste("PC1",loads[1],"%"))
  ylab<-c(paste("PC2",loads[2],"%"))
  if (is.null(colors)) colors=1
  plot(pcX$x[,1:2],xlab=xlab,ylab=ylab, col=colors, pch=formapunts, 
       xlim=c(min(pcX$x[,1])-100000, max(pcX$x[,1])+100000),ylim=c(min(pcX$x[,2])-100000, max(pcX$x[,2])+100000))
  text(pcX$x[,1],pcX$x[,2], labels, pos=3, cex=myCex)
  title(paste("Plot of first 2 PCs for expressions in", dataDesc, sep=" "), cex=0.8)
}

plotPCA(exprs(rawData), labels=sampleNames, dataDesc="raw data", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)

```

```{r}
pdf(file.path(resultsDir, "QCPlots_Raw.pdf"))
boxplot(rawData, which="all",las=2, main="Intensity distribution of RAW data", 
        cex.axis=0.6, col=sampleColor, names=sampleNames)
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of samples of RawData", 
     cex=0.7,  hang=-1)
plotPCA(exprs(rawData), labels=sampleNames, dataDesc="raw data", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)
dev.off()
```


```{r}
require("affyPLM")
eset <- normalize.ExpressionSet.invariantset(set)
#eset<-rma(rawData)

write.exprs(eset, file.path(resultsDir, "NormData.txt"))
```

```{r}
boxplot(eset, las=2, main="Intensity distribution of Normalized data", cex.axis=0.6, 
        col=sampleColor, names=sampleNames)
```

```{r}
clust.euclid.average <- hclust(dist(t(exprs(eset))),method="average")
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of NormData", 
     cex=0.7,  hang=-1)
```

```{r}
plotPCA <- function ( X, labels=NULL, colors=NULL, dataDesc="", scale=FALSE, formapunts=NULL, myCex=0.8,...)
{
  pcX<-prcomp(t(X), scale=scale) # o prcomp(t(X))
  loads<- round(pcX$sdev^2/sum(pcX$sdev^2)*100,1)
  xlab<-c(paste("PC1",loads[1],"%"))
  ylab<-c(paste("PC2",loads[2],"%"))
  if (is.null(colors)) colors=1
  plot(pcX$x[,1:2],xlab=xlab,ylab=ylab, col=colors, pch=formapunts, 
       xlim=c(min(pcX$x[,1])-10, max(pcX$x[,1])+10),ylim=c(min(pcX$x[,2])-10, max(pcX$x[,2])+10))
  text(pcX$x[,1],pcX$x[,2], labels, pos=3, cex=myCex)
  title(paste("Plot of first 2 PCs for expressions in", dataDesc, sep=" "), cex=0.8)
}

plotPCA(exprs(eset), labels=sampleNames, dataDesc="NormData", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)
```

```{r}
pdf(file.path(resultsDir, "QCPlots_Norm.pdf"))
boxplot(eset, las=2, main="Intensity distribution of Normalized data", cex.axis=0.6, 
        col=sampleColor, names=sampleNames)
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of NormData", 
     cex=0.7,  hang=-1)
plotPCA(exprs(eset), labels=sampleNames, dataDesc="selected samples", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)
dev.off()
```

```{r}
arrayQualityMetrics(eset,  reporttitle="QualityControl", force=TRUE)
```


```{r}
annotation(eset) <- "org.Mm.eg.db"
eset_filtered <- nsFilter(eset, var.func=IQR,
                          var.cutoff=0.75, var.filter=TRUE,
                          filterByQuantile=TRUE)
#NUMBER OF GENES OUT
print(eset_filtered$filter.log$numLowVar)

#NUMBER OF GENES IN
print(eset_filtered$eset)
```

```{r}
#CONTRAST MATRIX.lINEAR MODEL
treat <- targets$ShortName
lev <- factor(treat, levels = unique(treat))
lev
design <-model.matrix(~0+lev)
colnames(design) <- levels(lev)
rownames(design) <- sampleNames
print(design)
```

```{r}
cont.matrix1 <- makeContrasts( 
  a1.vs.a2 = a1-a2,
  a1.vs.b1 = a1-b1,
  a1.vs.b2 = a1-b2,
  a1.vs.c1 = a1-c1,
  a1.vs.c2 = a1-c2,
  a1.vs.d1 = a1-d1,
  a1.vs.d2 = a1-d2,
  a1.vs.e1 = a1-e1,
  a1.vs.e2 = a1-e2,
  a1.vs.f1 = a1-f1,
  a1.vs.f2 = a1-f2,
  a2.vs.b1 = a2-b1,
  a2.vs.b2 = a2-b2,
  a2.vs.c1 = a2-c1,
  a2.vs.c2 = a2-c2,
  a2.vs.d1 = a2-d1,
  a2.vs.d2 = a2-d2,
  a2.vs.e1 = a2-e1,
  a2.vs.e2 = a2-e2,
  a2.vs.f1 = a2-f1,
  a2.vs.f2 = a2-f2,
  b1.vs.b2 = b1-b2,
  b1.vs.c1 = b1-c1,
  b1.vs.c2 = b1-c2,
  b1.vs.d1 = b1-d1,
  b1.vs.d2 = b1-d2,
  b1.vs.e1 = b1-e1,
  b1.vs.e2 = b1-e2,
  b1.vs.f1 = b1-f1,
  b1.vs.f2 = b1-f2,
  b2.vs.c1 = b2-c1,
  b2.vs.c2 = b2-c2,
  b2.vs.d1 = b2-d1,
  b2.vs.d2 = b2-d2,
  b2.vs.e1 = b2-e1,
  b2.vs.e2 = b2-e2,
  b2.vs.f1 = b2-f1,
  b2.vs.f2 = b2-f2,
  c1.vs.c2 = c1-c2,
  c1.vs.d1 = c1-d1,
  c1.vs.d2 = c1-d2,
  c1.vs.e1 = c1-e1,
  c1.vs.e2 = c1-e2,
  c1.vs.f1 = c1-f1,
  c1.vs.f2 = c1-f2,
  c2.vs.d1 = c2-d1,
  c2.vs.d2 = c2-d2,
  c2.vs.e1 = c2-e1,
  c2.vs.e2 = c2-e2,
  c2.vs.f1 = c2-f1,
  c2.vs.f2 = c2-f2,
  d1.vs.d2 = d1-d2,
  d1.vs.e1 = d1-e1,
  d1.vs.e2 = d1-e2,
  d1.vs.f1 = d1-f1,
  d1.vs.f2 = d1-f2,
  d2.vs.e1 = d2-e1,
  d2.vs.e2 = d2-e2,
  d2.vs.f1 = d2-f1,
  d2.vs.f2 = d2-f2,
  e1.vs.e2 = e1-e2,
  e1.vs.f1 = e1-f1,
  e1.vs.f2 = e1-f2,
  e2.vs.f1 = e2-f1,
  e2.vs.f2 = e2-f2,
  f1.vs.f2 = f1-f2,
  levels = design)
  comparison1 <- "Effect of Induction"
```

```{r}
#MODEL FIT
fit1 <- lmFit(eset_filtered$eset, design)
fit.main1 <- contrasts.fit(fit1, cont.matrix1)
fit.main1
install.packages("limma")
#fit.main1 <- eBayes(fit.main1)
```

```{r}
#FILTER BY FALSE DISCOVERY RATE AND FOLD CHANGE
topTab <-  topTable (fit.main1, number=nrow(fit.main1), coef="Induced.vs.WT", adjust="fdr",lfc=abs(3))

#EXPORTED TO CSV AND HTML FILE
write.csv2(topTab, file= file.path(resultsDir,paste("Selected.Genes.in.comparison.",
                                                    comparison1, ".csv", sep = "")))

print(xtable(topTab,align="lllllll"),type="html",html.table.attributes="",
      file=paste("Selected.Genes.in.comparison.",comparison1,".html", sep=""))
```

```{r}
#VOLCANO PLOTS
volcanoplot(fit.main1, highlight=10, names=fit.main1$ID, 
            main = paste("Differentially expressed genes", colnames(cont.matrix1), sep="\n"))
abline(v = c(-3, 3))


pdf(file.path(resultsDir,"Volcanos.pdf"))
volcanoplot(fit.main1, highlight = 10, names = fit.main1$ID, 
            main = paste("Differentially expressed genes", colnames(cont.matrix1), sep = "\n"))
abline(v = c(-3, 3))
dev.off()

```

```{r}
#PREPARE THE DATA
my_frame <- data.frame(exprs(eset))
head(my_frame)
HMdata <- merge(my_frame, topTab, by.x = 0, by.y = 0)
rownames(HMdata) <- HMdata$Row.names
HMdata <- HMdata[, -c(1,10:15)]
head(HMdata)
HMdata2 <- data.matrix(HMdata, rownames.force=TRUE)
head(HMdata2)
write.csv2(HMdata2, file = file.path(resultsDir,"Data2HM.csv"))
```

```{r}
#HEATMAP PLOT
my_palette <- colorRampPalette(c("blue", "red"))(n = 299)

heatmap.2(HMdata2,
          Rowv=TRUE,
          Colv=TRUE,
          main="HeatMap Induced.vs.WT FC>=3",
          scale="row",
          col=my_palette,
          sepcolor="white",
          sepwidth=c(0.05,0.05),
          cexRow=0.5,
          cexCol=0.9,
          key=TRUE,
          keysize=1.5,
          density.info="histogram",
          ColSideColors=c(rep("red",4),rep("blue",4)),
          tracecol=NULL,
          srtCol=30)
```

```{r}
#EXPORT TO PDF FILE
pdf(file.path(resultsDir,"HeatMap InducedvsWT.pdf"))
heatmap.2(HMdata2,
          Rowv=TRUE,
          Colv=TRUE,
          main="HeatMap Induced.vs.WT FC>=3",
          scale="row",
          col=my_palette,
          sepcolor="white",
          sepwidth=c(0.05,0.05),
          cexRow=0.5,
          cexCol=0.9,
          key=TRUE,
          keysize=1.5,
          density.info="histogram",
          ColSideColors=c(rep("red",4),rep("blue",4)),
          tracecol=NULL,
          srtCol=30)
dev.off()
```

```{r}

all_anota<-data.frame(exprs(eset))
Annot <- data.frame(SYMBOL=sapply(contents(mogene10sttranscriptclusterSYMBOL), paste, collapse=", "),
                    DESC=sapply(contents(mogene10sttranscriptclusterGENENAME), paste, collapse=", "))
Annot<-Annot[!Annot$SYMBOL=="NA",]
Annot<-Annot[!Annot$DESC=="NA",]
head(Annot)

anotaGenes <- merge(Annot,all_anota, by.x=0,by.y=0)
head(anotaGenes)
write.table(anotaGenes, file ="data.ann.txt",sep="\t")

rownames(anotaGenes) <- anotaGenes[,1]
anotaGenes <- anotaGenes[,-1]
anotaGenes.end <- merge(anotaGenes, topTab, by.x=0,by.y=0)
#reordenamos las columnas
topTab.end <- anotaGenes.end[,c(1:3,12:17,4:11)]
topTab.end <- topTab.end[order(-topTab.end$B),]

rownames(topTab.end) <- topTab.end[,1]
topTab.end <- topTab.end[, -1]
write.csv(topTab.end, file = file.path(resultsDir,"TopTable.end.csv"))

```
